INSERT INTO [dbo].[Destinations] ([CountryName], [CityName]) VALUES
('United States', 'New York'),
('United Kingdom', 'London'),
('France', 'Paris'),
('Italy', 'Rome'),
('Japan', 'Tokyo'),
('Australia', 'Sydney'),
('Spain', 'Barcelona'),
('Germany', 'Berlin'),
('Canada', 'Toronto'),
('Netherlands', 'Amsterdam'),
('China', 'Beijing'),
('Brazil', 'Rio de Janeiro'),
('Russia', 'Moscow'),
('India', 'New Delhi'),
('Mexico', 'Mexico City'),
('Turkey', 'Istanbul'),
('United Arab Emirates', 'Dubai'),
('South Africa', 'Cape Town'),
('Thailand', 'Bangkok'),
('Greece', 'Athens'),
('Singapore', 'Singapore'),
('Malaysia', 'Kuala Lumpur'),
('Argentina', 'Buenos Aires'),
('South Korea', 'Seoul'),
('Sweden', 'Stockholm'),
('Switzerland', 'Zurich'),
('Austria', 'Vienna'),
('Belgium', 'Brussels'),
('Portugal', 'Lisbon'),
('Egypt', 'Cairo'),
('Norway', 'Oslo'),
('Denmark', 'Copenhagen'),
('Finland', 'Helsinki'),
('Poland', 'Warsaw'),
('Ireland', 'Dublin'),
('Czech Republic', 'Prague'),
('Hungary', 'Budapest'),
('New Zealand', 'Auckland'),
('Chile', 'Santiago'),
('Colombia', 'Bogota'),
('Saudi Arabia', 'Riyadh'),
('Israel', 'Tel-Aviv'),
('Indonesia', 'Jakarta'),
('Vietnam', 'Hanoi'),
('Philippines', 'Manila'),
('Hong Kong', 'Hong Kong'),
('Peru', 'Lima'),
('Pakistan', 'Karachi'),
('Bangladesh', 'Dhaka');